spring:
  application:
    name: fantasy-game

    datasource:
      url: jdbc:h2:mem:fantasy_db
      driver-class-name: org.h2.Driver
      username: sa
      password:

      h2:
        console:
          enabled: true
          path: /h2-console



.football-data.api:
  base-url: https://api.football-data.org/v4
  token:  396ab2521b284cd1915ec25349dc3c75