spring.datasource.url=jdbc:h2:mem:fantasy_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

football-data.api.url=https://api.football-data.org/v4
football-data.api.token=396ab2521b284cd1915ec25349dc3c75